services:

  mysql:
    image: mysql:8.4
    container_name: mysql-turnos
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema-turnos

  backend:
    build: .
    container_name: backend-turnos
    ports:
      - "8080:8080"
    depends_on:
      - mysql